"""
Explanation domain models — Phase 2D.

`ExplanationAgent` turns an already-finalised `ClaimDecision` plus its
supporting evidence (Policy/Financial/Fraud/Extraction results — all
already computed deterministically by earlier stages) into a structured,
member- and operations-facing explanation. It never introduces new facts,
never recalculates anything, and never overrides the decision — see
ARCHITECTURE.docx "8. Decision & Explanation" for the full rationale.

Rules (same as the rest of app/domain/):
- Pure Pydantic models. No database imports. No FastAPI imports. No AI SDK imports.
"""

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field

from app.domain.trace import AITraceMetadata


class ExplanationSource(str, Enum):
    """Where this explanation's text actually came from — never ambiguous.
    A caller must always be able to tell whether prose was AI-generated or
    a deterministic fallback (see docs/tradeoffs.md 'Fallback Explanation')."""

    AI = "AI"
    FALLBACK = "FALLBACK"


class ExplanationAIResponse(BaseModel):
    """
    The exact shape the LLM is asked to return (validated strictly —
    Pydantic raises on anything malformed, which ExplanationAgent treats
    the same as any other AI failure: fall back, never crash). Mirrors
    Phase 2B's discipline of validating AI output through a typed model
    before it ever reaches a domain object (app/domain/extraction.py's
    adapters), scaled down here since every field is already a plain
    string/list of strings — no Decimal/date sentinel parsing needed.
    """

    member_summary: str
    operations_summary: str
    key_reasons: List[str] = Field(default_factory=list)
    deductions: List[str] = Field(default_factory=list)
    policy_findings: List[str] = Field(default_factory=list)
    warnings: List[str] = Field(default_factory=list)
    next_action: str = ""


class ExplanationResult(BaseModel):
    """
    Output of ExplanationAgent.run() — one per claim that reached decision
    generation. Answers, in order: what was decided, how much was
    approved, why, which policy rules were involved, whether there were
    document issues, whether there were financial deductions, whether
    fraud/manual review was triggered, and whether processing was
    degraded — see ExplanationAgent's own docstring for how each field is
    populated deterministically from evidence, never invented.
    """

    member_summary: str = Field(description="Plain-language explanation for the member.")
    operations_summary: str = Field(description="More technical explanation for an ops reviewer.")
    key_reasons: List[str] = Field(default_factory=list, description="The main factors behind the decision.")
    deductions: List[str] = Field(
        default_factory=list, description="Human-readable financial deductions (copay, discount, caps)."
    )
    policy_findings: List[str] = Field(
        default_factory=list, description="The specific policy rules that affected this decision."
    )
    warnings: List[str] = Field(
        default_factory=list, description="Document/processing issues the member or ops should know about."
    )
    next_action: Optional[str] = Field(
        default=None, description="What the member should do next, if anything (e.g. resubmit with pre-auth)."
    )

    source: ExplanationSource = Field(
        description="AI = generated by the configured LLM from verified evidence; FALLBACK = the "
        "LLM call failed or returned an invalid response, so this is the deterministic fallback "
        "text built directly from the same evidence — see docs/tradeoffs.md."
    )
    degraded: bool = Field(
        default=False, description="True if this explanation is the fallback path (source=FALLBACK)."
    )
    confidence: float = Field(
        default=1.0, ge=0.0, le=1.0,
        description="Mirrors the decision's own confidence; lower for a FALLBACK explanation.",
    )
    ai_calls: List[AITraceMetadata] = Field(
        default_factory=list,
        description="Empty when source=FALLBACK (no successful AI call); one entry when the real "
        "explanation LLM call succeeded — same 'ai_calls' convention as DocumentVerificationResult/"
        "ClaimExtractionResult, consumed by ClaimsPipeline's ai_metadata_fn for the trace.",
    )
